---
- name: Add Redis GPG key
  ansible.builtin.get_url:
    url: https://packages.redis.io/gpg
    dest: /etc/apt/trusted.gpg.d/redis.asc
    mode: '0644'

- name: Add redis apt repository
  ansible.builtin.apt_repository:
    repo: "deb https://packages.redis.io/deb {{ ansible_facts['distribution_release'] }} main"
    state: present
    filename: redis

- name: Install redis-server from apt
  ansible.builtin.apt:
    name: redis-server
    state: present
    update_cache: yes

- name: Allow external connections (bind 0.0.0.0)
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^bind '
    line: 'bind 0.0.0.0'

- name: Disable protected mode
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^protected-mode '
    line: 'protected-mode no'

- name: Disable RDB persistence (snapshots)
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^save'
    line: 'save ""'

- name: Disable AOF persistence
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^appendonly '
    line: 'appendonly no'

- name: Enable multi-thread
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^io-threads'
    line: 'io-threads 3' # redis recommends cores - 1

- name: Use threads for reading
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^io-threads-do-reads'
    line: 'io-threads-do-reads yes'

- name: Restart service
  ansible.builtin.service:
    name: redis-server
    state: restarted
    enabled: true
