---
- name: Add KeyDB GPG key
  ansible.builtin.get_url:
    url: https://download.keydb.dev/open-source-dist/keyring.gpg
    dest: /etc/apt/trusted.gpg.d/keydb.gpg
    mode: '0644'

- name: Add keydb apt repository
  ansible.builtin.apt_repository:
    repo: "deb https://download.keydb.dev/open-source-dist {{ ansible_facts['distribution_release'] }} main"
    state: present
    filename: keydb

- name: Install keydb
  ansible.builtin.apt:
    name: keydb
    update_cache: yes

# --- Configuration for External Access ---
- name: Allow external connections (bind 0.0.0.0)
  ansible.builtin.lineinfile:
    path: /etc/keydb/keydb.conf
    regexp: '^bind '
    line: 'bind 0.0.0.0'

- name: Disable protected mode
  ansible.builtin.lineinfile:
    path: /etc/keydb/keydb.conf
    regexp: '^protected-mode '
    line: 'protected-mode no'

- name: Disable RDB persistence (snapshots)
  ansible.builtin.lineinfile:
    path: /etc/keydb/keydb.conf
    regexp: '^save'
    line: 'save ""'

- name: Disable AOF persistence
  ansible.builtin.lineinfile:
    path: /etc/keydb/keydb.conf
    regexp: '^appendonly '
    line: 'appendonly no'

# These settings to not exist for keydb
# - name: Enable multi-thread
#   ansible.builtin.lineinfile:
#     path: /etc/keydb/keydb.conf
#     regexp: '^io-threads'
#     line: 'io-threads 3'
#
# - name: Use threads for reading
#   ansible.builtin.lineinfile:
#     path: /etc/keydb/keydb.conf
#     regexp: '^io-threads-do-reads'
#     line: 'io-threads-do-reads yes'

- name: Restart service
  ansible.builtin.service:
    name: keydb-server
    state: restarted
    enabled: true
