##############
# Create GCP instances to host the SUTs and benchmarking software
# 
# Related: https://developers.redhat.com/articles/2023/07/12/how-create-instance-gcp-using-ansible-cli#how_to_use_ansible_cli
##############
- name: Create GCP instances
  hosts: localhost
  gather_facts: false
  vars:
    project: "ace-wording-477310-h0"
    machine_type: "n4-highcpu-4"
    ubuntu_2204: "projects/ubuntu-os-cloud/global/images/ubuntu-2204-jammy-v20251203"
    ubuntu_2404: "projects/ubuntu-os-cloud/global/images/ubuntu-2404-noble-amd64-v20251121"
    zone: "europe-north2-a" # Choosing this region, since n4 cpu limit is 72 instead of 24
    machines:
      # Choose the tested SUT here by commenting / uncommenting
      # 8 Machines max
      - "Redis1" # 1
      - "Redis2" # 1
      - "Redis3" # 1
      - "Redis4" # 1
      - "Redis5" # 1
      # - "Valkey1" # 2
      # - "Valkey2" # 2
      # - "Valkey3" # 2
      # - "Valkey4" # 2
      # - "Valkey5" # 2
      # - "KeyDB1" # 3
      # - "KeyDB2" # 3
      # - "KeyDB3" # 3
      # - "KeyDB4" # 3
      # - "KeyDB5" # 3
      # - "Acdis1" # 4
      # - "Acdis2" # 4
      # - "Acdis3" # 4
      # - "Acdis4" # 4
      # - "Acdis5" # 4
      - "Bench1"
      - "Bench2"
      - "Bench3"

  tasks:
    - name: Create instance
      google.cloud.gcp_compute_instance:
        name: "{{ item | lower }}"
        machine_type: "{{ machine_type }}"
        disks:
          - auto_delete: true
            boot: true
            initialize_params:
              source_image: "{{ ubuntu_2204 if item.startswith('KeyDB') else ubuntu_2404 }}"
        network_interfaces:
          - network:
              name: "default"
            access_configs:
              - name: External NAT
                type: ONE_TO_ONE_NAT
        tags:
          items:
            - redis-server
        zone: "{{ zone }}"
        auth_kind: "serviceaccount"
        project: "{{ project }}"
        service_account_contents: "{{ gcp_service_account }}"
        service_accounts: # Link our service account, needed for monitoring agent to work
          - email: "ansible@ace-wording-477310-h0.iam.gserviceaccount.com"
            scopes: 
             - "https://www.googleapis.com/auth/cloud-platform"
        state: "present"
        status: RUNNING
      loop: "{{ machines }}"
      register: instance_data
    
    - name: Create firewall rule
      google.cloud.gcp_compute_firewall:
        name: "allow-redis-ingress"
        network:
          name: "default"
        project: "{{ project }}"
        auth_kind: "serviceaccount"
        service_account_contents: "{{ gcp_service_account }}"
        allowed:
          - ip_protocol: tcp
            ports:
              - "6379"
              - "7000"
              - "16379" # "By default, the cluster bus port is set by adding 10000 to the data port"
              - "17000"
        # Applies this rule only to instances with this tag
        target_tags:
          - redis-server
        source_ranges:
          - "0.0.0.0/0"
        state: present

    - name: Print details
      debug:
        msg: "Instance '{{ item.name }}' created with IP {{ item.networkInterfaces[0].accessConfigs[0].natIP | default('???') }}"
      loop: "{{ instance_data.results }}"
      loop_control: { label: "{{ item.name | default('SKIPPED') }}" }
      when: not item.failed

    - name: Report failures
      debug:
        msg: "FAILED to create instance '{{ item.item }}'. Error: {{ item.msg | default(item.body.error.message) }}"
      loop: "{{ instance_data.results }}"
      when: item.failed
      loop_control:
        label: "{{ item.item | default('FAILED ITEM') }}"
