- name: Run benchmark
  become: yes
  gather_facts: yes
  hosts:
    - bench1
    - bench2
    - bench3
  tasks:
    # - name: Run benchmark
    #   ansible.builtin.shell: 
    #     # cmd: "sudo /opt/benchmarker/benchmark -a {{ target_ip }} -c etc -r 20000000 -t 32 -o {{ output_file }}"
    #     cmd: "sudo /opt/benchmarker/benchmark -a {{ target_ip }} -c etc -r 20000000 -t 32 --cluster -o {{output_file}}"

    - name: Run benchmark
      ansible.builtin.shell: 
        cmd: >
          sudo /opt/benchmarker/benchmark 
          -a {{ target_ip }} 
          {{ '--port 7000' if ',' in target_ip else '' }} 
          -c etc 
          -r 20000000 
          -t 32 
          {{ '--cluster' if ',' in target_ip else '' }} 
          -o {{ output_file }}

    - name: Find csv
      find:
        paths: "/home/nils/"
        file_type: file
        patterns: '*.csv'
      register: csv_list

    - name: Download csv
      ansible.builtin.fetch:
        src: "{{ item.path }}"
        dest: "./results/{{ inventory_hostname }}/"
        flat: yes
      loop: "{{ csv_list.files }}"

