#########
# Run this to stop all instances.
# ! This does not delete them !
#########
---
- name: Stop all running GCP instances in a zone
  hosts: localhost
  gather_facts: false
  vars:
    gcp_project: "ace-wording-477310-h0"
    gcp_zone: "europe-north2-a"
  roles:
    - role: gcp_stop_vms
