- name: Install GCP agent
  become: yes
  hosts: all
  tasks:
    - name: Download GCP ops agent
      ansible.builtin.get_url: 
        url: https://dl.google.com/cloudagents/add-google-cloud-ops-agent-repo.sh
        dest: "/tmp/add-gcp-agent.sh"

    - name: Install
      ansible.builtin.shell:
        cmd: "sudo bash /tmp/add-gcp-agent.sh --also-install"

- name: Configure redis node
  hosts: redis
  become: yes
  tasks:
    - name: Import redis tasks
      ansible.builtin.import_tasks: ./tasks/install_redis.yml
  handlers:
    - name: Restart redis
      ansible.builtin.service:
        name: redis-server
        state: restarted

- name: Configure keydb
  hosts: keydb
  become: yes
  tasks:
    - name: Import keydb tasks
      ansible.builtin.import_tasks: ./tasks/install_keydb.yml
  handlers:
    - name: Restart keydb
      ansible.builtin.service:
        name: keydb-server
        state: restarted

- name: Configure valkey
  hosts: valkey
  become: yes
  tasks:
    - name: Import valkey tasks
      ansible.builtin.import_tasks: ./tasks/install_valkey.yml
  handlers:
    - name: Restart valkey
      ansible.builtin.service:
        name: valkey-server
        state: restarted

- name: Configure acdis
  hosts: acdis
  become: yes
  tasks:
    - name: Import acdis tasks
      ansible.builtin.import_tasks: ./roles/acdis/tasks/main.yml

- name: Configure benchmarker
  hosts:
    - bench1
    - bench2
    - bench3
  become: yes
  tasks:
    - name: Import benchmarker tasks
      ansible.builtin.import_tasks: ./roles/benchmarker/tasks/main.yml

- name: Generate env file
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create environment variable file from GCP inventory
      template:
        src: "./roles/gcp_create_vms/files/vars.j2"
        dest: "./gcp_hosts.env"
        mode: '0600'
