##############
# Create GCP instances to host the SUTs and benchmarking software
# 
# Related: https://developers.redhat.com/articles/2023/07/12/how-create-instance-gcp-using-ansible-cli#how_to_use_ansible_cli
##############

- name: Create GCP instances
  hosts: localhost
  gather_facts: false
  vars:
    project: "ace-wording-477310-h0"
    # machine_type: "e2-micro" # TODO
    machine_type: "n4-highcpu-4" # TODO
    ubuntu_2204: "projects/ubuntu-os-cloud/global/images/ubuntu-2204-jammy-v20251203"
    ubuntu_2404: "projects/ubuntu-os-cloud/global/images/ubuntu-2404-noble-amd64-v20251121"
    zone: "europe-west9-b"
    machines:
      - "Valkey"
      - "Bench1"
      - "Bench2"
      - "Bench3"
      # - "Acdis"
      # - "Redis"
      # - "KeyDB"

  tasks:
    - name: Create instance
      google.cloud.gcp_compute_instance:
        name: "{{ item | lower }}"
        machine_type: "{{ machine_type }}"
        disks:
          - auto_delete: true
            boot: true
            initialize_params:
              source_image: "{{ ubuntu_2204 if item == 'KeyDB' else ubuntu_2404 }}"
        network_interfaces:
          - network:
              name: "default"
            access_configs:
              - name: External NAT
                type: ONE_TO_ONE_NAT
        tags:
          items:
            - redis-server
        zone: "{{ zone }}"
        auth_kind: "serviceaccount"
        project: "{{ project }}"
        service_account_contents: "{{ gcp_service_account }}"
        service_accounts: # Link our service account, needed for monitoring agent to work
          - email: "ansible@ace-wording-477310-h0.iam.gserviceaccount.com"
            scopes: 
             - "https://www.googleapis.com/auth/cloud-platform"
        state: "present"
        status: RUNNING
      loop: "{{ machines }}"
      register: instance_data
    
    - name: Create firewall rule for Redis (6379)
      google.cloud.gcp_compute_firewall:
        name: "allow-redis-ingress"
        network:
          name: "default"
        project: "{{ project }}"
        auth_kind: "serviceaccount"
        service_account_contents: "{{ gcp_service_account }}"
        allowed:
          - ip_protocol: tcp
            ports:
              - "6379"
        # Applies this rule only to instances with this tag
        target_tags:
          - redis-server
        # Allows traffic from anywhere (adjust 0.0.0.0/0 if you need to restrict source IPs)
        source_ranges:
          - "0.0.0.0/0"
        state: present

    - name: Print details
      debug:
        msg: "Instance '{{ item.name }}' created with IP {{ item.networkInterfaces[0].accessConfigs[0].natIP | default('???') }}"
      loop: "{{ instance_data.results }}"
      loop_control: { label: "{{ item.name | default('SKIPPED') }}" }
      when: not item.failed # Only print for successful items

    - name: Report failures
      debug:
        msg: "FAILED to create instance '{{ item.item }}'. Error: {{ item.msg | default(item.body.error.message) }}"
      loop: "{{ instance_data.results }}"
      when: item.failed # Only print for failed items
      loop_control:
        label: "{{ item.item | default('FAILED ITEM') }}"
