- name: Configure redis node
  hosts: redis
  become: yes
  tasks:
    - name: Import redis tasks
      ansible.builtin.import_tasks: ./tasks/install_redis.yml
  handlers:
    - name: Restart redis
      ansible.builtin.service:
        name: redis-server
        state: restarted
- name: 
  hosts: keydb
  become: yes
  tasks:
    - name: Import keydb tasks
      ansible.builtin.import_tasks: ./tasks/install_keydb.yml
  handlers:
    - name: Restart keydb
      ansible.builtin.service:
        name: keydb-server
        state: restarted
